// brand
        $(function () {
            var brand_auto = [
                "Alfa Romeo (อัลฟาโรเมโอ)",
                "Aston Martin (แอสตันมาร์ติน)",
                "Audi (อาวดี้)",
                "Austin (ออสติน)",
                "Bentley (เบนท์ลี่ )",
                "BMW (บีเอ็มดับเบิ้ลยู)",
                "Cadillac (คาดิลแลค) ",
                "Cherry (เชอร์รี่)",
                "Chevrolet (เชฟโรเลต)",
                "Chryler (ไครสเลอร์)",
                "Citroen (ซีครอง)",
                "Daihatsu (ไดฮัทสุ)",
                "Datsun (ดัทสัน)",
                "DEVA (ดีว่า)",
                "DFM (ดีเอฟเอ็ม)",
                "Douge (ดอร์จ)",
                "Ferrari (เฟอร์รารี)",
                "Fiat (เฟียท) ",
                "Ford (ฟอร๋ด)",
                "Foton (โฟตอน)",
                "GMC (จีอ็มซี) ",
                "Holden (โฮลเดน)",
                "Honda (ฮอนด้า)",
                "Hummer (ฮัมเมอร์)",
                "Hyundai (ฮุนได)",
                "Infinity (อินฟินิตี้)",
                "Isuzu (อีซูซุ)",
                "Jaguar (จากัวร์)",
                "Jeep (จีป)",
                "Joylong (จอยลอง)",
                "Kia (เกีย)",
                "Lamborghini (แลมโบกินี่ )",
                "Land Lover (เรนจ์ โรเวอร์)",
                "Lexus (เล็กซัส)",
                "LINCOLN (ลิงคอล์น)",
                "Lotus (โลตัส)",
                "Maserati (มาเซราตี)",
                "Mazda (มาสด้า)",
                "McLaren (แมคลาเรน)",
                "Mercedes-Benz (เมอร์เซเดส-เบนซ์)",
                "MG (เอ็มจี)",
                "Mini (มินิ)",
                "Mitsubishi (มิตซูบิชิ)",
                "Mitsuoka (มิตซูโอกะ )",
                "Morris (มอร์ริส)",
                "Nissan (นิสสัน)",
                "Oldsmobile",
                "Opel (โอเปิล )",
                "Perodua (เปอโรดัว )",
                "Peugeot (เปอโยต์)",
                "Playmount",
                "Pontiac (พอนทิแอค)",
                "Porsche (ปอร์เช่)",
                "Proton (โปรตอน)",
                "Rely",
                "Rolls-Royce (โรลส์-รอยซ์)",
                "Rover (โรเวอร์)",
                "Saab (ซ้าบ)",
                "Seat",
                "Skoda (สโกด้า)",
                "Smart (สมาร์ท)",
                "Ssangyoung (ซันยอง)",
                "Subaru (ซูบารุ)",
                "Suzuki (ซูซูกิ)",
                "Tata (ทาทา)",
                "Tesla (เทสล่า)",
                "Toyota (โตโยต้า)",
                "TR",
                "Volkswagen (โฟล์กสวาเกน)",
                "Volvo (วอลโว่)",
                "Aprilia",
                "Benelli (เบนลี่)",
                "BMW (บีเอ็มดับเบิ้ลยู)",
                "CFMOTO",
                "Ducati (ดูคาติ)",
                "GPX (จีพีเอกซ์)",
                "Harley-Davidson (ฮาเรย์ เดวิสชั่น)",
                "Honda (ฮอนด้า)",
                "Husqvarna",
                "Kawasaki (คาวาซากิ)",
                "Keeway (คีเวย์)",
                "KTM (เคทีเอ็ม)",
                "Moto (โมโต)",
                "Guzzi (กัสซิ)",
                "Moto (โมโต)",
                "Parilla (พาลิลล่า)",
                "MV-Agusta (เอ็มวีออกัสต้า)",
                "Peugeot (เปอร์โย)",
                "Scooter",
                "Piaggio",
                "Royal",
                "Alloy",
                "Royal Enfield (รอยอล เอนฟิลด์)",
                "Scomadi (สโกมาดิ)",
                "Stallions (สตาเลี่ยน)",
                "Suzuki (ซูซูกิ)",
                "SYM (เอส วาย เอ็ม)",
                "Triumph (ไทรอั้ม)",
                "Vespa (เวสป้า)",
                "Yamaha (ยามาฮ่า)",
                "Zero",
                "Motorcycles",
                "Zongshen",
                "Ryuka"
                


            ];
            $("#brand_auto").autocomplete({
                source: brand_auto
            });
        });

// series
        $(function () {
        var series_auto = [
        "156",
        "Giulia",
        "Giuliteta",
        "Cygnet",
        "DB11",
        "DB9",
        "Rapide",
        "V12",
        "V8",
        "Vanquish",
        "80",
        "A1",
        "A3",
        "A4",
        "A5",
        "A6",
        "A7",
        "A8",
        "Q2",
        "Q3",
        "Q5",
        "Q7",
        "R8",
        "RS3",
        "RS5",
        "S3",
        "TT",
        "TT RS",
        "TTS",
        "A90 Atlantic",
        "Arnage",
        "Bentayga",
        "Continental",
        "Flying Spur",
        "Mulsanne",
        "Turbo",
        "de Ville",
        "Eldorado",
        "Escalade",
        "Fleetwood",
        "QQ",
        "Allroader",
        "Astro",
        "Aveo (อาร์วีโอ้)",
        "Camero (คาเมโล)",
        "Carprice",
        "Captiva (แคปติว่า)",
        "Colorado (โคโรลาโด้)",
        "Corvette",
        "Cruze (ครูช)",
        "Express",
        "Optra (ออบตร้า)",
        "Savana",
        "Sonic (โซนิค)",
        "Spin (สปิน)",
        "Trailblazer (เทรลเบเซอร์)",
        "Van ",
        "Zafira",
        "300C",
        "300M",
        "Neon",
        "PT Cruiser",
        "Serbring",
        "Voyager",
        "BX",
        "C3",
        "C4",
        "C5",
        "C8",
        "DS3",
        "Jumper",
        "Xantia",
        "Xsara",
        "Mira",
        "Opti",
        "620",
        "Hercules",
        "Mini Truck",
        "Mini VAN",
        "Saver",
        "Truck",
        "C Series",
        "348 Spider",
        "458 Italia",
        "458 Speciale",
        "458 Spider",
        "488 GTB",
        "812 Superfast",
        "CALIFORNIA",
        "California T",
        "F12 Berlinetta",
        "F355",
        "F360",
        "F430",
        "F599 Fiorano",
        "GTC4 Lusso",
        "500",
        "500C",
        "850 Spider",
        "Ducato",
        "Punto",
        "Aspire",
        "EcoSport (อีโค่สปอร์ต)",
        "Escape (เอสเคป)",
        "Everest (เอฟเวอร์เรส)",
        "Explorer",
        "Festiva",
        "Fiesta (เฟียสต้า)",
        "Focus (โฟกัส)",
        "Laser",
        "Lincoln Continental",
        "Marathon",
        "Mustang (มัสแตง)",
        "Ranger (แรงเจอร์)",
        "Territory",
        "Aunmark",
        "Columbus",
        "View",
        "Savana",
        "Calais",
        "Accord (แอคคอร์ด)",
        "BR-V (บี อาร์ วี)",
        "Brio (บริโอ)",
        "City (ซิตี้)",
        "Civic (ซีวิค)",
        "CR-V (ซี อาร์ วี)",
        "CR-X",
        "CR-Z",
        "CROSSROAD",
        "Elysion",
        "Fit (ฟิต)",
        "Freed (ฟรีด)",
        "HR-V (เอช อาร์ วี)",
        "Integra",
        "Jazz (แจ๊ส)",
        "Legend",
        "N-ONE",
        "NSX (เอ็น เอา เอกซ์)",
        "Odyssey (ออดีสซี่)",
        "Prelude (พรีหรูด)",
        "S2000 (เอส ทูทาวซั่น)",
        "STEPWGN SPADA (สเตปวาก้อน สปาด้า)",
        "Stream (สตรีม)",
        "Today",
        "H1 (เอชวัน)",
        "H2",
        "H3",
        "Accent",
        "Elanta (อีแลนต้า)",
        "Grand Starex (แกรนด์สตาร์เร็ก)",
        "H-1 (เอชวัน)",
        "Sonata (โซนาต้า)",
        "Tiburon",
        "Tucson (ทรัสซอน)",
        "Veloster (เวลอสเตอร์)",
        "G",
        "M",
        "Adventure",
        "Adventure Master",
        "Cameo",
        "D-Max (ดีแมกซ์)",
        "Dragon Eyes (ดราก้อน อายด์)",
        "Dragon Power (ดราก้อน พาวเวอร์)",
        "ELF",
        "Grand Adventure",
        "MU-7 (มิวเซเว่น)",
        "MU-X (มิงเอกซ์)",
        "TFR",
        "Tripper",
        "Trooper",
        "Vega",
        "Wanderer",
        "Daimler",
        "F-Pace",
        "F-Type",
        "S-Type",
        "Sovereing",
        "X-Type",
        "XF",
        "XJ",
        "XJ6",
        "XJ8",
        "XJS",
        "XK8",
        "Cherokee",
        "Grand Cherokee",
        "Wrangler",
        "A6",
        "Carens",
        "Carnival",
        "Grand Carnival",
        "Jumbo",
        "K2500",
        "K2900",
        "Picanto",
        "Rio",
        "Sorento",
        "Soul",
        "Aventador",
        "Diablo",
        "Gallardo",
        "Harucane",
        "Mucielago",
        "Defender",
        "Discovery",
        "Discovery 3",
        "Discovery Sport",
        "Freelander",
        "Freelander 2",
        "Range Rover",
        "Ct200h",
        "ES300",
        "ES300h",
        "GS200t",
        "GS250",
        "GS300",
        "GS300h",
        "IS250",
        "IS300h",
        "LS400",
        "LS430",
        "LS460",
        "LS460L",
        "LX470",
        "NX300h",
        "RC300h",
        "RX200t",
        "RX270",
        "RX300",
        "RX350",
        "SC430",
        "Aviator",
        "Elise",
        "Esprit",
        "Erova",
        "Exige",
        "Ghibli",
        "Grancabrio",
        "Granturismo",
        "Levante",
        "Quattroporte",
        "2 (มาสด้า สอง)",
        "3 (มาสด้า สาม)",
        "323",
        "6",
        "626",
        "BT-50 (บีที 50) ",
        "BT-50 Pro (บีที 50 โปร)",
        "CX-3 (ซีเอกซ์ สาม)",
        "CX-5 (ซีเอกซ์ ห้า)",
        "CX-7",
        "CX-9",
        "Familia",
        "Fighter",
        "Lantis",
        "Magnum Thunder",
        "MPV",
        "MX-5",
        "RX-7",
        "RX-8",
        "Tribute",
        "650S",
        "675LT",
        "MP4-12C",
        "A170",
        "A180",
        "A180 CDI",
        "A200",
        "A250",
        "A45",
        "B180",
        "B180 CDI",
        "B200",
        "C180",
        "C180 AMG",
        "C180 Kompressor",
        "C200",
        "C200 CGI",
        "C200 Kompressor",
        "C220",
        "C220 CDI",
        "C230",
        "C230 Kompressor",
        "C240",
        "C250",
        "C250 CDI",
        "C250 CGI",
        "C300",
        "C32 AMG",
        "C350",
        "C43",
        "C55 AMG",
        "C63 AMG",
        "CL500",
        "CL500 AMG",
        "CLA180",
        "CLA200",
        "CLA250 AMG",
        "CLC200 Kompressor",
        "CLK200",
        "CLK200 Kompressor",
        "CLK230 Kompressor",
        "CLK240",
        "CLS350 CDI",
        "CLS220 CDI",
        "CLS250 CDI",
        "CLS250 CDI AMG",
        "CLS350 ",
        "CLS500",
        "CLS55 AMG",
        "E200",
        "E200 CGI",
        "E200 Kompressor",
        "E200D",
        "E220",
        "E200 CDI",
        "E230",
        "E240",
        "E250",
        "E250 AMG",
        "E250 CDI",
        "E250 CGI",
        "E250 CGI AMG",
        "E270 CDI",
        "E280",
        "E300",
        "E350",
        "E350 AMG",
        "E63 AMG",
        "GL350",
        "GLA200",
        "GLA250",
        "GLC250",
        "GLE250",
        "GLE350",
        "GLE500",
        "GLS350",
        "ML250 CDI",
        "ML250 CDI AMG",
        "ML270",
        "ML280 CDI",
        "ML320",
        "ML350 CDI",
        "R300 CDI",
        "R350",
        "S280",
        "S300",
        "S320",
        "S320 CDI",
        "S350",
        "S350 CDI",
        "S400",
        "S430",
        "S500",
        "S55 AMG",
        "S600",
        "SL280",
        "SL300",
        "SL350",
        "SL500",
        "SL55 AMG",
        "SL63 AMG",
        "SLC300",
        "SLC43",
        "SLK200",
        "SLK200 AMG",
        "SLK200 Kompressor",
        "SLK200 Kompressor AMG",
        "SLK230 Kompressor",
        "SLK250",
        "SLK280",
        "SLK350",
        "SLS AMG",
        "V250",
        "Viano",
        "Vito",
        "GS (จีเอส)",
        "MG3 (เอ็มจี 3)",
        "MG5 (เอ็มจี 5)",
        "MG6 (เอ็มจี 6)",
        "ZS (แซดเอส)",
        "Austin",
        "Cooper",
        "One",
        "3000GT",
        "Attrage (เอททราส)",
        "Canter",
        "Colt",
        "Cylone",
        "Delica Space Wagon",
        "Evolution (อีโวลูชั่น)",
        "Fuso",
        "Galant",
        "L300",
        "Lancer (แลนเซอร์)",
        "Lancer EX (แลนเซอร์ อีเอกซ์)",
        "Mirage (มิราจ)",
        "Outlander",
        "Pajero",
        "Pajero Junior",
        "Pajero Sport (ปาเจโร สปอร์ต)",
        "Space Wagon",
        "Strada",
        "Strada G-Wagon",
        "Triton (ไทรตัน)",
        "Himiko",
        "Le-Seyde",
        "Mini",
        "200SX",
        "350Z",
        "370Z",
        "Almera (อัลเมร่า)",
        "Big M",
        "Bluebird Atessa",
        "Cedric",
        "Cefiro",
        "Cube (คิ้ว)",
        "Elgrand",
        "Frontier (ฟรอนเทียร์)",
        "Frontier Navara",
        "GT-R (จีทีอาร์)",
        "Infiniti",
        "Juke (จู้ค)",
        "Leaf (ลีฟ)",
        "Livina (ลาวิน่า)",
        "March (มาร์ช)",
        "Micra",
        "Murano",
        "Note (โน้ต)",
        "NP 300 Navara (เอ็นพี 300)",
        "NV",
        "NX",
        "Presea",
        "President",
        "Primera",
        "Pulsa (พัลซ่า)",
        "Serena",
        "Silivia",
        "Skyline",
        "Sunny",
        "Sylphy (ซิลฟี่)",
        "Teana (เทียน่า)",
        "Terra",
        "Terrano II",
        "Tiida (ทีด้า)",
        "Urvan",
        "X-Trail (เอ๊กซ์เทรล)",
        "Xciter",
        "Cutlass",
        "Corsa",
        "Omega",
        "Kancill",
        "206",
        "207",
        "3008",
        "306",
        "307",
        "308",
        "405",
        "406",
        "407",
        "408",
        "508",
        "605",
        "807",
        "Expert",
        "RCZ",
        "Valiant",
        "Fiero",
        "718",
        "911 Carrera",
        "911 Carrera 4 GTS",
        "911 Carrera 4S",
        "911 Carrera GTS",
        "911 Carrera S",
        "911 GT3",
        "911 GT3 RS",
        "911 Targa",
        "911 Targa 4",
        "911 Targa 4 GTS",
        "911 Targa 4S",
        "911 Turbo",
        "Boxster",
        "Cayenne",
        "Cayman",
        "Macan",
        "Panamera",
        "Exora",
        "Gen2",
        "Persona",
        "Preve",
        "Saga",
        "Savvy",
        "Yo-Ki",
        "Corniche II",
        "Dawn",
        "Ghost",
        "Silver Dawn",
        "Silver Shadow",
        "Silver Spur",
        "Wraith",
        "Mini",
        "9-3",
        "9-5",
        "900",
        "9000",
        "Alhambra",
        "Octavia",
        "City",
        "Forfour",
        "Fortwo",
        "Roadster",
        "Actyon",
        "Kyron",
        "Stavic",
        "BRZ",
        "Forester",
        "Impreza",
        "Legacy",
        "Levorg",
        "Outback",
        "R2",
        "XV",
        "APV",
        "Caribian",
        "Carry",
        "Celerio (เซเลริโอ้)",
        "Ciaz (เซียส)",
        "Ertiga (เออติก้า)",
        "Lapin",
        "Swift (สวิฟต์)",
        "SX4 (เอสเอกซ์โฟร์)",
        "Vitara",
        "Super Ace Mint",
        "Superace",
        "Xenon",
        "Model S",
        "Model X",
        "4Runner",
        "86 GT",
        "Alphard (อัลพาร์ด)",
        "Altezza",
        "Avanza (อแวนซ่า)",
        "Aygo",
        "bB",
        "Caldina",
        "Camry (แคมรี่)",
        "Carina",
        "Celica",
        "Century (เซ็นจูรี่)",
        "Corolla",
        "Colrolla Altis (โคโรร่า อัลติส)",
        "Corona",
        "Cressida",
        "Crown (คราวน์)",
        "Esquire",
        "Estima (เอสทิม่า)",
        "FJ CRUISER",
        "Fortuner (ฟอร์จูนเนอร์)",
        "Grand Hiace",
        "Granvia",
        "Harrier (แฮร์ริเออร์)",
        "Hiace",
        "Hikux Mighty-X",
        "Hilux Revo (รีโว่)",
        "Hiliux Surf",
        "Hilux Tiger (ไทเกอร์)",
        "Hilux Vigo (วีโก้)",
        "Innova (อินโนวา)",
        "iQ",
        "Kluger",
        "Land Criser",
        "Landcruiser Prado",
        "LN",
        "Lucida",
        "Mark X",
        "MR-S",
        "MR2",
        "Platz",
        "Porte",
        "Prius (พรีอุส)",
        "Rav4",
        "Sienta (เซียนต้า)",
        "Soarer",
        "Soluna",
        "Sport Cruiser",
        "Sport Rider",
        "Stalet",
        "Super Custom",
        "Super Wagon",
        "Supra",
        "TERCEL",
        "Vellfire (เวลไฟล์)",
        "Ventury",
        "Vios (วีออส)",
        "Vista",
        "Vitz",
        "Voxy",
        "Wish (วิช)",
        "Yaris (ยาริส)",
        "Yaris Ativ (ยาริส เอทีฟ)",
        "Transformer II",
        "Beetle",
        "Caravelle",
        "Classic Van",
        "Golf",
        "Multivan",
        "New Beetle",
        "Passat",
        "Passat CC",
        "Scirocco",
        "Touareg",
        "Transporter",
        "Vento",
        "244",
        "460",
        "740",
        "760",
        "850",
        "940",
        "960",
        "C30",
        "S40",
        "S60",
        "S70",
        "S80",
        "S90",
        "V40",
        "V50",
        "V60",
        "V70",
        "V90",
        "XC60",
        "XC90",
        "RSV4",
        "Tuono",
        "302R",
        "BN600i",
        "Leoncino",
        "TNT",
        "TRE1130K",
        "TRK502",
        "TRK502X",
        "TNT1130R",
        "TNT135",
        "TNT25",
        "TNT300S",
        "TNT600GT",
        "TNT899",
        "G310GS",
        "G310R",
        "F700",
        "F750",
        "F800",
        "R1200",
        "R1250",
        "R-NINE-T",
        "K1600",
        "C400X",
        "C650GT",
        "S1000R",
        "S1000RR",
        "S1000XR",
        "250NK",
        "1299 Panigale",
        "959 Panigale",
        "Diavel",
        "Hypermotard",
        "Monster",
        "Multistrada",
        "Panigale",
        "Panigale R",
        "Scramble",
        "Supersport",
        "CR5",
        "Demon",
        "Demon X 125",
        "DP",
        "Legend",
        "RAZER",
        "CVO",
        "Softail",
        "Sportster",
        "Street",
        "Touring",
        "CB (ซีบี)",
        "CBR (ซีบีอาร์)",
        "Click i (คลิก ไอ)",
        "CRF",
        "CTX",
        "Dream (ดรีม)",
        "Forza 300 (ฟอร์ซ่า 300)",
        "Goldwing (โกลด์วิง)",
        "Integra",
        "Monkey (มังกี้)",
        "Moove (มูฟ)",
        "MSX125 (เอ็ม เอส เอกซ์)",
        "NC",
        "NM4",
        "PCX (พีซีเอกซ์)",
        "RC123V",
        "Rebel",
        "Scoopy i (สกู๊ปปี้ ไอ)",
        "Sh150i",
        "Spacy i",
        "Super Cup (ซูเปอร์คัพ)",
        "VFR",
        "Wave (เวฟ)",
        "X-ADV",
        "Zoomer-X (ซูเมอร์ ดอกซ์)",
        "1400GTR",
        "D-Tracker (ดีแทรกเกอร์)",
        "KLX",
        "KSR (เคเอสอาร์)",
        "Ninja (นินจา)",
        "Versys",
        "Vulcan",
        "W",
        "Z (แซด)",
        "Blackster",
        "Dorado250",
        "RVK200",
        "Superlight 200",
        "TX 200",
        "TXM 200",
        "1090",
        "1190",
        "1290",
        "200 Duke",
        "250 Duke",
        "390 Duke ",
        "690",
        "790 Duke",
        "Bullet 500",
        "Classic 500",
        "Continental GT",
        "Himalayan",
        "VTR",
        "Centaur",
        "VanVan",
        "Burgman",
        "GSX",
        "Let's",
        "Smash",
        "Shogun",
        "GD110",
        "946",
        "GTS",
        "LT",
        "LXV",
        "Primavera",
        "PX",
        "S",
        "Spirint",
        "Aerox 155",
        "Exciter 150",
        "FINN",
        "Fino (ฟัโน่)",
        "Grand Filano (แกรนด์ฟิลาโย่)",
        "M-Slaz (เอ็มสแลส)",
        "MT03",
        "MT07",
        "MT09",
        "NMAX (เอ็นแมกซ์)",
        "Qbix (คิวบิค)",
        "Spark (สปาร์ค)",
        "TMAX",
        "XMAX",
        "Tricity",
        "SR400",
        "R15 (อาร์15)",
        "R3 (อาร์3)",
        "R6"


        ];
        $("#series_auto").autocomplete({
        source: series_auto
        });
    });

    
$(function () {
    var places_auto = [
        "หน้าคอมเพล็กซ์",
        "ตรงข้ามสนามบาสเกตบอล",
        "3 แยกอาคาร3 คณะเภสัชศาสตร์",
        "สามแยกหอ 3",
        "แยกอุทยานเกษตร",
        "หลังคอมเพล็กซ์",
        "ประตู 089 (ประตู 9 )",
        "ถนนสาย 4 แยกประตู 6",
        "สามแยกไฟแดงหน้าสำนักงาน รปภ",
        "แยกคณะเทคโนโลยี",
        "ยูเทิร์นจามจุรี",
        "หน้าหอพักอินเตอร์",
        "หมู่บ้านศูนย์แพทย์ 3 ",
        "สี่แยกศาลาเดิม",
        "ถนนมอดินแดง จุดกลับรถองค์การนักศึกษา",
        "หน้า สนง รปภ",
        "หน้าคณะ พยาบาล",
        "หน้าสถาบันวิจัยและพัฒนาลุ่มน้ำโขง",
        "หน้าหอพักชายที่ 9",
        "สามแยกคณะสาธารณสุข",
        "ทางลำรองข้างสะพานขาวด้านทิศตะวันออก",
        "ถ.มอดินแดง หน้าสมาคมศิษย์เก่า",
        "ถนนมอดินแดงขาออกใกล้แยกมอดินแดงกลาง",
        "วงเวียนโลตาแลค",
        "แฟลตแก่นคูณ",
        "สามแยกสะพานขาว",
        "ใต้สะพานลอยคอมเพล็กซ์",
        "แยกศูนย์แพทย์ 6",
        "ประตู 12",
        "สามแยกหน้าคณะสถาปัตย์",
        "ประตู 8 หนองแวง",
        "แยกโรงเรียนสาธิตอุบาล",
        "ฝั่งตรงข้ามอาคาร 5 คณะมนุษย์",
        "สามแยกหอพัก 8 หลัง",
        "ตรงข้ามแปลงเกษตร",
        "หน้าตึกอธิการบดี ตรงข้ามหน่วยปฏิบัติการพิเศษ",
        "อาคาร 50 ปี ",
        "ทางโค้งหลังสาธิตจะออกประตู 11",
        "ถนนหน้าอาคาร FM 103",
        "หน้าซอย 12",
        "ถนนหน้าโรงอาหารหอพักแพทย์",
        "หน้าโรงพิมพ์มหาวิทยาลัยขอนแก่น",
        "ทางเข้าหอพักอินเตอร์",
        "ซอย1 หอศิลปวัฒนธรรม",
        "หน้าหอพัก 2 ทิศตะวันตกคอมเพล็ก",
        "ทางออกปั้ม ปตท.",
        "4 แยกประตู 2 ศาลเจ้าพ่อมอดินแดง",
        "ประตู 4",
        "แยกแฟลตป่าดู่",
        "ถนนสีฐาน แยกป่าดู่",
        "แยกสนามเทนนิส",
        "ถนนสายสี่ 8/13",
        "หน้าโรงอาหารชาย",
        "แยกป่าดู่ 12",
        "ป้ายรถเมย์หน้าสถาบันขงจื่อ",
        "ถนนสาย 4 แยกซอย 11 ป่าดู่",
        "ถนนสีฐานใกล้ทางแยกกีฬา 2",
        "ถ.สหศาสตร์ ติดบ้านชีวาศิลป์",
        "หน้าหอพักชายที่ 12",
        "ถนนหน้าโรงเรียนสาธิตอนุบาลศึกษาศาสตร์",
        "ถ. มอดินแดง แยกสวนรุกชาติ",
        "ตรงข้ามสวนรุกขชาติ ",
        "บริเวณประตูหอ 19",
        "แยกหอที่ 13",
        "ประตู 2",
        "ทางเข้าศูนย์แพทย์ 1",
        "ถ.สีฐานตรงข้ามกับ ซอย 5 ",
        "ถนนทางเข้าสำนักงานกีฬา",
        "หอพักชายที่ 10",
        "ถนนหน้าอาคารพละ",
        "ทางโค้งบ้านพักศูนย์แพทย์ 5",
        "ลานจอดรถประตู 5 สีฐาน",
        "ทางแยกคอมเพล็กซ์",
        "หน้าประตูหอพัก 26 ",
        "หน้าทางเข้าสนามยิงปืน ",
        "ด้านหลังศูนย์ประชุม",
        "สี่แยกทางออกประตู 3",
        "หน้าอาคาร 5 คณะมนุษย์",
        "ทางแยกหอพักชายที่ 9",
        "ถนนสาย 4 ตึกสัตวศาสตร์",
        "แยกสนามเบสบอล",
        "ถนนหน้าสนามเปตอง ",
        "ประตู 5",
        "ทางเข้าอาคารพจน์ สารสิน ",
        "ลานจอดรถคอมเพล้กซ์",
        "ลานจอดเซเว่น หน้าคณะมนุษย์",
        "แยกศูนย์ประชุม",
        "ถนนหน้าแฟลตจามจุรี",
        "หน้าตึกคณะวิทยาลัยปกครองท้องถิ่น",
        "หน้าหอศิลปวัฒนธรรม ถ.สีฐาน",
        "แยกหอ 16 ",
        "ประตู 087",
        "ทางออกสวนรุกขชาติ แฟลตจามจุรี",
        "ด้านหลังหอ 3",
        "หลังโรงเรียนสาธิตศึกษาศาสตร์ ทางออก ป.0811",
        "ถนนมอดินแดงด้านศูนย์สารสนเทศ",
        "ตรงข้ามสำนักงานรักษาความปลอดภัยและการจราจร",
        "ถนนหน้าอาคารพิมลกลกิจ",
        "ด้านหน้าคณะทันตกรรม",
        "แยกศูนย์แพทย์ 4",
        "วงเวียนสิริคุณากร",
        "ถนนสาย 4",
        "ถนนมอดินแดง",
        "ถนนสีฐาน",
        "ถนนวิทยวัฒนา",
        "ถนนแก่นร่มเกล้า",
        "ถนนแก่นวิชาการ",
        "ถนนสหศาสตร์",
        "ถนนสุขศิลป์",
        "ถนนวิทยวัฒนา 1"

    ];
    $("#places_auto").autocomplete({
        source: places_auto
    });
});

    